## **Working with Excel**

In [1]:
import pandas as pd

In [ ]:
excel_file = pd.read_excel("ipl_pandas_practice.xlsx",index_col="Match_ID")  # first sheet ->Matches
excel_file

         Team1 Team2      Venue Winner  Runs_Team1  Runs_Team2
Match_ID
1          CSK    MI     Mumbai     MI         185         188
2          RCB   KKR  Bengaluru    RCB         201         190
3           LQ    GT  Ahmedabad     GT         165         168
4          SRH    DC      Delhi    SRH         210         180
5           RR  PBKS     Jaipur     RR         175         160
6           MI   RCB     Mumbai     MI         195         185
7          KKR   SRH    Kolkata    KKR         180         172
8           GT   CSK  Ahmedabad    CSK         170         175

In [8]:
# for second sheet
sheet2 = pd.read_excel("ipl_pandas_practice.xlsx",sheet_name="Players")
sheet2

   Player_ID          Player Team          Role  Matches  Runs  Wickets
0        101     Virat Kohli  RCB        Batter        6   285        0
1        102    Rohit Sharma   MI        Batter        6   240        0
2        103        MS Dhoni  CSK  Wicketkeeper        5   125        0
3        104  Jasprit Bumrah   MI        Bowler        6    20       10
4        105     Rashid Khan   GT        Bowler        5    45        8
5        106     Pat Cummins  SRH        Bowler        6    55        9
6        107    Sanju Samson   RR  Wicketkeeper        5   210        0
7        108   Andre Russell  KKR   All-rounder        6   160        7

In [12]:
# reading text files --> use read_csv -> find seperator in txt file
txt_file = pd.read_csv("tab_separated_data.txt",sep="\t")
txt_file

     Name  Age               Department  Semester       City
0  Hammad   19             Data Science         1  Islamabad
1     Ali   20         Computer Science         2     Lahore
2    Sara   19  Artificial Intelligence         1    Karachi
3   Ahmed   21     Software Engineering         3   Peshawar
4  Ayesha   20             Data Science         2     Multan

## **Working with JSON & SQL**